### ISSUE TITLE
Please update to 1.19.2

### ISSUE THREAD

**Issue by mrniddala** [haykam821/Mod-Viewer#4]

**Comment by haykam821** [comment]
While [version 1.1.0](https://github.com/haykam821/Mod-Viewer/releases/tag/1.1.0) does not natively support Minecraft 1.19.2 with the bundled version of SGUI, you can override the bundled version of SGUI with [an updated SGUI version that supports Minecraft 1.19.2](https://github.com/Patbox/sgui/releases/tag/1.1.5%2B1.19.1).

**Comment by mrniddala** [comment]
Hello @haykam821, sorry for the late response.
Everything works, thanks! I think this can be closed now 😊
